"""initial schema

Revision ID: a074610b4bbb
Revises:
Create Date: 2026-08-28 12:46:48.183783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a074610b4bbb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_audit_log",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=32), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("intent", sa.String(length=50), nullable=True),
        sa.Column("tool", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.String(length=10), nullable=True),
        sa.Column("success", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_audit_log_id"), "ai_audit_log", ["id"], unique=False)
    op.create_index(op.f("ix_ai_audit_log_request_id"), "ai_audit_log", ["request_id"], unique=False)
    op.create_index(op.f("ix_ai_audit_log_tenant_id"), "ai_audit_log", ["tenant_id"], unique=False)
    op.create_table(
        "ai_conversations",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_conversations_external_id"), "ai_conversations", ["external_id"], unique=True)
    op.create_index(op.f("ix_ai_conversations_id"), "ai_conversations", ["id"], unique=False)
    op.create_index(op.f("ix_ai_conversations_tenant_id"), "ai_conversations", ["tenant_id"], unique=False)
    op.create_table(
        "ai_messages",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_messages_conversation_id"), "ai_messages", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_ai_messages_id"), "ai_messages", ["id"], unique=False)
    op.create_index(op.f("ix_ai_messages_tenant_id"), "ai_messages", ["tenant_id"], unique=False)
    op.create_table(
        "cash_movements",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("balance_after", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cash_movements_created", "cash_movements", ["created_at"], unique=False)
    op.create_index(op.f("ix_cash_movements_id"), "cash_movements", ["id"], unique=False)
    op.create_index("ix_cash_movements_reference", "cash_movements", ["reference_type", "reference_id"], unique=False)
    op.create_index(op.f("ix_cash_movements_tenant_id"), "cash_movements", ["tenant_id"], unique=False)
    op.create_index("ix_cash_movements_type", "cash_movements", ["type"], unique=False)
    op.create_table(
        "clients",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=True),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("telefone", sa.String(), nullable=False),
        sa.Column("telefone_secundario", sa.String(), nullable=True),
        sa.Column("rua", sa.String(), nullable=False),
        sa.Column("numero", sa.String(), nullable=False),
        sa.Column("complemento", sa.String(), nullable=True),
        sa.Column("referencia", sa.String(), nullable=True),
        sa.Column("bairro", sa.String(), nullable=False),
        sa.Column("observacoes", sa.String(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telefone", name="uq_clients_telefone"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_client_tenant_codigo"),
    )
    op.create_index("ix_clients_ativo", "clients", ["ativo"], unique=False)
    op.create_index(op.f("ix_clients_codigo"), "clients", ["codigo"], unique=False)
    op.create_index("ix_clients_email", "clients", ["email"], unique=False)
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_index("ix_clients_telefone", "clients", ["telefone"], unique=False)
    op.create_index(op.f("ix_clients_tenant_id"), "clients", ["tenant_id"], unique=False)
    op.create_index("ix_clients_tipo", "clients", ["tipo"], unique=False)
    op.create_table(
        "delivery_drivers",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=True),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("telefone", sa.String(), nullable=False),
        sa.Column("placa", sa.String(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_driver_tenant_codigo"),
    )
    op.create_index(op.f("ix_delivery_drivers_codigo"), "delivery_drivers", ["codigo"], unique=False)
    op.create_index(op.f("ix_delivery_drivers_id"), "delivery_drivers", ["id"], unique=False)
    op.create_index(op.f("ix_delivery_drivers_tenant_id"), "delivery_drivers", ["tenant_id"], unique=False)
    op.create_table(
        "expenses",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("payment_method", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_expenses_category", "expenses", ["category"], unique=False)
    op.create_index("ix_expenses_date", "expenses", ["date"], unique=False)
    op.create_index(op.f("ix_expenses_id"), "expenses", ["id"], unique=False)
    op.create_index("ix_expenses_status", "expenses", ["status"], unique=False)
    op.create_index(op.f("ix_expenses_tenant_id"), "expenses", ["tenant_id"], unique=False)
    op.create_table(
        "financial_ledger",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_financial_ledger_id"), "financial_ledger", ["id"], unique=False)
    op.create_index(op.f("ix_financial_ledger_tenant_id"), "financial_ledger", ["tenant_id"], unique=False)
    op.create_index("ix_ledger_created", "financial_ledger", ["created_at"], unique=False)
    op.create_index("ix_ledger_event_type", "financial_ledger", ["event_type"], unique=False)
    op.create_index("ix_ledger_reference", "financial_ledger", ["reference_type", "reference_id"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_codigo", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("minimum_quantity", sa.Integer(), nullable=False),
        sa.Column("maximum_quantity", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "product_codigo", name="uq_inventory_tenant_product"),
    )
    op.create_index(op.f("ix_inventory_id"), "inventory", ["id"], unique=False)
    op.create_index(op.f("ix_inventory_product_codigo"), "inventory", ["product_codigo"], unique=False)
    op.create_index(op.f("ix_inventory_tenant_id"), "inventory", ["tenant_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_codigo", sa.String(), nullable=False),
        sa.Column("product_codigo", sa.String(), nullable=False),
        sa.Column("product_nome", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_items_id"), "order_items", ["id"], unique=False)
    op.create_index(op.f("ix_order_items_order_codigo"), "order_items", ["order_codigo"], unique=False)
    op.create_index(op.f("ix_order_items_tenant_id"), "order_items", ["tenant_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=True),
        sa.Column("client_codigo", sa.String(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("delivery_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(), nullable=True),
        sa.Column("payment_status", sa.String(), nullable=False),
        sa.Column("address_snapshot", sa.String(), nullable=False),
        sa.Column("delivery_driver_codigo", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_order_tenant_codigo"),
    )
    op.create_index(op.f("ix_orders_client_codigo"), "orders", ["client_codigo"], unique=False)
    op.create_index(op.f("ix_orders_codigo"), "orders", ["codigo"], unique=False)
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(op.f("ix_orders_tenant_id"), "orders", ["tenant_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_codigo", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("reference", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("ix_payments_created", "payments", ["created_at"], unique=False)
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index("ix_payments_order", "payments", ["order_codigo"], unique=False)
    op.create_index(op.f("ix_payments_order_codigo"), "payments", ["order_codigo"], unique=False)
    op.create_index("ix_payments_status", "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_tenant_id"), "payments", ["tenant_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=True),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("preco", sa.Float(), nullable=False),
        sa.Column("estoque", sa.Integer(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_product_tenant_codigo"),
    )
    op.create_index(op.f("ix_products_codigo"), "products", ["codigo"], unique=False)
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False)
    op.create_table(
        "receivables",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_codigo", sa.String(), nullable=False),
        sa.Column("order_codigo", sa.String(), nullable=False),
        sa.Column("original_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_receivables_customer", "receivables", ["customer_codigo"], unique=False)
    op.create_index(op.f("ix_receivables_customer_codigo"), "receivables", ["customer_codigo"], unique=False)
    op.create_index("ix_receivables_due_date", "receivables", ["due_date"], unique=False)
    op.create_index(op.f("ix_receivables_id"), "receivables", ["id"], unique=False)
    op.create_index("ix_receivables_order", "receivables", ["order_codigo"], unique=False)
    op.create_index(op.f("ix_receivables_order_codigo"), "receivables", ["order_codigo"], unique=False)
    op.create_index("ix_receivables_status", "receivables", ["status"], unique=False)
    op.create_index(op.f("ix_receivables_tenant_id"), "receivables", ["tenant_id"], unique=False)
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_codigo", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("balance_before", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reference_type", "reference_id", "product_codigo", "type", name="uq_stock_movements_reference_product_type"
        ),
    )
    op.create_index("ix_stock_movements_created", "stock_movements", ["created_at"], unique=False)
    op.create_index(op.f("ix_stock_movements_id"), "stock_movements", ["id"], unique=False)
    op.create_index("ix_stock_movements_product", "stock_movements", ["product_codigo"], unique=False)
    op.create_index(op.f("ix_stock_movements_product_codigo"), "stock_movements", ["product_codigo"], unique=False)
    op.create_index("ix_stock_movements_reference", "stock_movements", ["reference_type", "reference_id"], unique=False)
    op.create_table(
        "whatsapp_conversations",
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("client_codigo", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("human_operator", sa.String(length=100), nullable=True),
        sa.Column("draft_json", sa.Text(), nullable=True),
        sa.Column("last_message", sa.Text(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "phone_number", name="uq_wa_conversation_account_phone"),
    )
    op.create_index("ix_wa_conversation_status", "whatsapp_conversations", ["status"], unique=False)
    op.create_index(
        op.f("ix_whatsapp_conversations_account_id"), "whatsapp_conversations", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_whatsapp_conversations_client_codigo"), "whatsapp_conversations", ["client_codigo"], unique=False
    )
    op.create_index(op.f("ix_whatsapp_conversations_id"), "whatsapp_conversations", ["id"], unique=False)
    op.create_index(
        op.f("ix_whatsapp_conversations_phone_number"), "whatsapp_conversations", ["phone_number"], unique=False
    )
    op.create_index(op.f("ix_whatsapp_conversations_tenant_id"), "whatsapp_conversations", ["tenant_id"], unique=False)
    op.create_table(
        "whatsapp_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("provider_message_id", sa.String(length=200), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("sender", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("message_type", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("raw_payload", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["whatsapp_conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_message_id"),
    )
    op.create_index(
        "ix_wa_message_conversation_created", "whatsapp_messages", ["conversation_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_whatsapp_messages_conversation_id"), "whatsapp_messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_whatsapp_messages_id"), "whatsapp_messages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whatsapp_messages_id"), table_name="whatsapp_messages")
    op.drop_index(op.f("ix_whatsapp_messages_conversation_id"), table_name="whatsapp_messages")
    op.drop_index("ix_wa_message_conversation_created", table_name="whatsapp_messages")
    op.drop_table("whatsapp_messages")
    op.drop_index(op.f("ix_whatsapp_conversations_tenant_id"), table_name="whatsapp_conversations")
    op.drop_index(op.f("ix_whatsapp_conversations_phone_number"), table_name="whatsapp_conversations")
    op.drop_index(op.f("ix_whatsapp_conversations_id"), table_name="whatsapp_conversations")
    op.drop_index(op.f("ix_whatsapp_conversations_client_codigo"), table_name="whatsapp_conversations")
    op.drop_index(op.f("ix_whatsapp_conversations_account_id"), table_name="whatsapp_conversations")
    op.drop_index("ix_wa_conversation_status", table_name="whatsapp_conversations")
    op.drop_table("whatsapp_conversations")
    op.drop_index("ix_stock_movements_reference", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_product_codigo"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_product", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_id"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_created", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_receivables_tenant_id"), table_name="receivables")
    op.drop_index("ix_receivables_status", table_name="receivables")
    op.drop_index(op.f("ix_receivables_order_codigo"), table_name="receivables")
    op.drop_index("ix_receivables_order", table_name="receivables")
    op.drop_index(op.f("ix_receivables_id"), table_name="receivables")
    op.drop_index("ix_receivables_due_date", table_name="receivables")
    op.drop_index(op.f("ix_receivables_customer_codigo"), table_name="receivables")
    op.drop_index("ix_receivables_customer", table_name="receivables")
    op.drop_table("receivables")
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_products_codigo"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_payments_tenant_id"), table_name="payments")
    op.drop_index("ix_payments_status", table_name="payments")
    op.drop_index(op.f("ix_payments_order_codigo"), table_name="payments")
    op.drop_index("ix_payments_order", table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_index("ix_payments_created", table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_orders_tenant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_codigo"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_codigo"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_order_items_tenant_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_codigo"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_inventory_tenant_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_product_codigo"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_id"), table_name="inventory")
    op.drop_table("inventory")
    op.drop_index("ix_ledger_reference", table_name="financial_ledger")
    op.drop_index("ix_ledger_event_type", table_name="financial_ledger")
    op.drop_index("ix_ledger_created", table_name="financial_ledger")
    op.drop_index(op.f("ix_financial_ledger_tenant_id"), table_name="financial_ledger")
    op.drop_index(op.f("ix_financial_ledger_id"), table_name="financial_ledger")
    op.drop_table("financial_ledger")
    op.drop_index(op.f("ix_expenses_tenant_id"), table_name="expenses")
    op.drop_index("ix_expenses_status", table_name="expenses")
    op.drop_index(op.f("ix_expenses_id"), table_name="expenses")
    op.drop_index("ix_expenses_date", table_name="expenses")
    op.drop_index("ix_expenses_category", table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_delivery_drivers_tenant_id"), table_name="delivery_drivers")
    op.drop_index(op.f("ix_delivery_drivers_id"), table_name="delivery_drivers")
    op.drop_index(op.f("ix_delivery_drivers_codigo"), table_name="delivery_drivers")
    op.drop_table("delivery_drivers")
    op.drop_index("ix_clients_tipo", table_name="clients")
    op.drop_index(op.f("ix_clients_tenant_id"), table_name="clients")
    op.drop_index("ix_clients_telefone", table_name="clients")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_index("ix_clients_email", table_name="clients")
    op.drop_index(op.f("ix_clients_codigo"), table_name="clients")
    op.drop_index("ix_clients_ativo", table_name="clients")
    op.drop_table("clients")
    op.drop_index("ix_cash_movements_type", table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_tenant_id"), table_name="cash_movements")
    op.drop_index("ix_cash_movements_reference", table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_id"), table_name="cash_movements")
    op.drop_index("ix_cash_movements_created", table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index(op.f("ix_ai_messages_tenant_id"), table_name="ai_messages")
    op.drop_index(op.f("ix_ai_messages_id"), table_name="ai_messages")
    op.drop_index(op.f("ix_ai_messages_conversation_id"), table_name="ai_messages")
    op.drop_table("ai_messages")
    op.drop_index(op.f("ix_ai_conversations_tenant_id"), table_name="ai_conversations")
    op.drop_index(op.f("ix_ai_conversations_id"), table_name="ai_conversations")
    op.drop_index(op.f("ix_ai_conversations_external_id"), table_name="ai_conversations")
    op.drop_table("ai_conversations")
    op.drop_index(op.f("ix_ai_audit_log_tenant_id"), table_name="ai_audit_log")
    op.drop_index(op.f("ix_ai_audit_log_request_id"), table_name="ai_audit_log")
    op.drop_index(op.f("ix_ai_audit_log_id"), table_name="ai_audit_log")
    op.drop_table("ai_audit_log")
    # ### end Alembic commands ###
