"""baseline multi-tenant schema

Revision ID: e4840d746bde
Revises: 
Create Date: 2026-08-10 01:21:59.986827

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e4840d746bde'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('plano', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('telefone_secundario', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'codigo', name='uq_clients_company_codigo')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_telefone'), ['telefone'], unique=False)

    op.create_table('delivery_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('placa', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'codigo', name='uq_drivers_company_codigo')
    )
    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_drivers_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_drivers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_drivers_id'), ['id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'codigo', name='uq_products_company_codigo')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('delivery_driver_id', sa.Integer(), nullable=True),
    sa.Column('client_codigo', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('delivery_driver_codigo', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('address_snapshot', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['delivery_driver_id'], ['delivery_drivers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'codigo', name='uq_orders_company_codigo')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_client_codigo'), ['client_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_delivery_driver_id'), ['delivery_driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_delivery_driver_id'))
        batch_op.drop_index(batch_op.f('ix_orders_company_id'))
        batch_op.drop_index(batch_op.f('ix_orders_codigo'))
        batch_op.drop_index(batch_op.f('ix_orders_client_id'))
        batch_op.drop_index(batch_op.f('ix_orders_client_codigo'))

    op.drop_table('orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_company_id'))
        batch_op.drop_index(batch_op.f('ix_products_codigo'))

    op.drop_table('products')
    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_company_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_codigo'))

    op.drop_table('delivery_drivers')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_telefone'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))
        batch_op.drop_index(batch_op.f('ix_clients_company_id'))
        batch_op.drop_index(batch_op.f('ix_clients_codigo'))

    op.drop_table('clients')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))
        batch_op.drop_index(batch_op.f('ix_companies_codigo'))

    op.drop_table('companies')
    # ### end Alembic commands ###
