"""baseline: schema atual completo (39 tabelas)

Revision ID: 12f8390d5be4
Revises: 
Create Date: 2026-09-04 09:25:43.900537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f8390d5be4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_log',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('tool', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('auth_audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_auth_audit_actor', ['actor_id'], unique=False)
        batch_op.create_index('ix_auth_audit_tenant', ['tenant_id'], unique=False)
        batch_op.create_index('ix_auth_audit_timestamp', ['timestamp'], unique=False)

    op.create_table('auth_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_auth_membership_user_tenant')
    )
    with op.batch_alter_table('auth_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_auth_membership_tenant', ['tenant_id'], unique=False)
        batch_op.create_index('ix_auth_membership_user', ['user_id'], unique=False)

    op.create_table('auth_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('system_role', sa.String(length=30), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_auth_role_name')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_auth_session_token')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_auth_session_status', ['status'], unique=False)
        batch_op.create_index('ix_auth_session_user', ['user_id'], unique=False)

    op.create_table('auth_tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_auth_tenant_id')
    )
    op.create_table('auth_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_auth_user_username')
    )
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.create_index('ix_auth_user_status', ['status'], unique=False)

    op.create_table('automation_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('customer_codigo', sa.String(), nullable=False),
    sa.Column('customer_nome', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_executions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_executions_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_executions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('confidence_filter', sa.String(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('max_messages_per_day', sa.Integer(), nullable=True),
    sa.Column('cooldown_days', sa.Integer(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('total_executions', sa.Integer(), nullable=True),
    sa.Column('successful_sends', sa.Integer(), nullable=True),
    sa.Column('failed_sends', sa.Integer(), nullable=True),
    sa.Column('opted_out_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cash_movements',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index('ix_cash_movements_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_id'), ['id'], unique=False)
        batch_op.create_index('ix_cash_movements_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_cash_movements_type', ['type'], unique=False)

    op.create_table('clients',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('telefone_secundario', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_client_tenant_codigo'),
    sa.UniqueConstraint('tenant_id', 'telefone', name='uq_client_tenant_telefone')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('ix_clients_ativo', ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_codigo'), ['codigo'], unique=False)
        batch_op.create_index('ix_clients_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index('ix_clients_telefone', ['telefone'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_clients_tipo', ['tipo'], unique=False)

    op.create_table('delivery_drivers',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('placa', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_driver_tenant_codigo')
    )
    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_drivers_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_drivers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_drivers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('delivery_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('customer_codigo', sa.String(length=10), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_complement', sa.String(length=100), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip_code', sa.String(length=10), nullable=True),
    sa.Column('address_reference', sa.String(length=200), nullable=True),
    sa.Column('address_lat', sa.Float(), nullable=True),
    sa.Column('address_lng', sa.Float(), nullable=True),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.String(length=50), nullable=True),
    sa.Column('failure_notes', sa.Text(), nullable=True),
    sa.Column('proof_type', sa.String(length=30), nullable=True),
    sa.Column('proof_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('driver_notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_delivery_idempotency')
    )
    with op.batch_alter_table('delivery_records', schema=None) as batch_op:
        batch_op.create_index('ix_delivery_order', ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_records_delivery_id'), ['delivery_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_delivery_records_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_records_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_delivery_tenant_driver', ['tenant_id', 'driver_id'], unique=False)
        batch_op.create_index('ix_delivery_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('driver_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_locations', schema=None) as batch_op:
        batch_op.create_index('ix_driver_loc_tenant_driver', ['tenant_id', 'driver_id'], unique=False)

    op.create_table('driver_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_driver_session_token')
    )
    with op.batch_alter_table('driver_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_driver_session_driver', ['driver_id'], unique=False)
        batch_op.create_index('ix_driver_session_tenant', ['tenant_id'], unique=False)

    op.create_table('expenses',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expenses_category', ['category'], unique=False)
        batch_op.create_index('ix_expenses_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)
        batch_op.create_index('ix_expenses_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('financial_ledger',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_ledger_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_ledger_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_ledger_created', ['created_at'], unique=False)
        batch_op.create_index('ix_ledger_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_ledger_reference', ['reference_type', 'reference_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_idempotency_key')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_tenant', ['tenant_id'], unique=False)

    op.create_table('inventory',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_codigo', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_quantity', sa.Integer(), nullable=False),
    sa.Column('maximum_quantity', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_codigo', name='uq_inventory_tenant_product')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_product_codigo'), ['product_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('order_items',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_codigo', sa.String(), nullable=False),
    sa.Column('product_codigo', sa.String(), nullable=False),
    sa.Column('product_nome', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_codigo'), ['order_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('orders',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('client_codigo', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('address_snapshot', sa.String(), nullable=False),
    sa.Column('delivery_driver_codigo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_order_tenant_codigo')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_client_codigo'), ['client_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('outbox_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_entries', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_status', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_outbox_tenant', ['tenant_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('fee_value', sa.Float(), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_payment_method_tenant_code')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index('ix_payment_method_tenant', ['tenant_id'], unique=False)

    op.create_table('payments',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_codigo', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index('ix_payments_order', ['order_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_order_codigo'), ['order_codigo'], unique=False)
        batch_op.create_index('ix_payments_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pix_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('key_type', sa.String(length=20), nullable=False),
    sa.Column('holder_name', sa.String(length=200), nullable=False),
    sa.Column('holder_document', sa.String(length=20), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('copy_paste_code', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pix_configs', schema=None) as batch_op:
        batch_op.create_index('ix_pix_config_tenant', ['tenant_id'], unique=False)

    op.create_table('products',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_product_tenant_codigo')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('receivables',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_codigo', sa.String(), nullable=False),
    sa.Column('order_codigo', sa.String(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receivables', schema=None) as batch_op:
        batch_op.create_index('ix_receivables_customer', ['customer_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_customer_codigo'), ['customer_codigo'], unique=False)
        batch_op.create_index('ix_receivables_due_date', ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_id'), ['id'], unique=False)
        batch_op.create_index('ix_receivables_order', ['order_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_order_codigo'), ['order_codigo'], unique=False)
        batch_op.create_index('ix_receivables_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('route_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_records', schema=None) as batch_op:
        batch_op.create_index('ix_route_driver', ['driver_id'], unique=False)
        batch_op.create_index('ix_route_status', ['status'], unique=False)
        batch_op.create_index('ix_route_tenant', ['tenant_id'], unique=False)

    op.create_table('route_stop_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('address_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_stop_records', schema=None) as batch_op:
        batch_op.create_index('ix_route_stop_route', ['route_id'], unique=False)

    op.create_table('segments',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('rule_logic', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_id'), ['id'], unique=False)
        batch_op.create_index('ix_segments_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_segments_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('service_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('order_codigo', sa.String(length=50), nullable=False),
    sa.Column('customer_codigo', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method_code', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pix_key_used', sa.String(length=200), nullable=True),
    sa.Column('pix_copy_paste', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_notes', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('provider_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.create_index('ix_service_payment_order', ['order_id'], unique=False)
        batch_op.create_index('ix_service_payment_status', ['status'], unique=False)
        batch_op.create_index('ix_service_payment_tenant', ['tenant_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_codigo', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_type', 'reference_id', 'product_codigo', 'type', name='uq_stock_movements_reference_product_type')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movements_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_id'), ['id'], unique=False)
        batch_op.create_index('ix_stock_movements_product', ['product_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_codigo'), ['product_codigo'], unique=False)
        batch_op.create_index('ix_stock_movements_reference', ['reference_type', 'reference_id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('capacity_total', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_driver_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'plate', name='uq_vehicle_tenant_plate')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('whatsapp_conversations',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('client_codigo', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('human_operator', sa.String(length=100), nullable=True),
    sa.Column('draft_json', sa.Text(), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'phone_number', name='uq_wa_conversation_account_phone')
    )
    with op.batch_alter_table('whatsapp_conversations', schema=None) as batch_op:
        batch_op.create_index('ix_wa_conversation_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversations_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversations_client_codigo'), ['client_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversations_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('vehicle_capacities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('product_codigo', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'product_codigo', name='uq_capacity_vehicle_product')
    )
    with op.batch_alter_table('vehicle_capacities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_capacities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_capacities_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('vehicle_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('product_codigo', sa.String(), nullable=False),
    sa.Column('loaded', sa.Integer(), nullable=True),
    sa.Column('reserved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'product_codigo', name='uq_load_vehicle_product')
    )
    with op.batch_alter_table('vehicle_loads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_loads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_loads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.create_index('ix_wa_message_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_conversation_id'))
        batch_op.drop_index('ix_wa_message_conversation_created')

    op.drop_table('whatsapp_messages')
    with op.batch_alter_table('vehicle_loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_loads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_loads_id'))

    op.drop_table('vehicle_loads')
    with op.batch_alter_table('vehicle_capacities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_capacities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_capacities_id'))

    op.drop_table('vehicle_capacities')
    with op.batch_alter_table('whatsapp_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversations_phone_number'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversations_client_codigo'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversations_account_id'))
        batch_op.drop_index('ix_wa_conversation_status')

    op.drop_table('whatsapp_conversations')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_reference')
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_codigo'))
        batch_op.drop_index('ix_stock_movements_product')
        batch_op.drop_index(batch_op.f('ix_stock_movements_id'))
        batch_op.drop_index('ix_stock_movements_created')

    op.drop_table('stock_movements')
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_service_payment_tenant')
        batch_op.drop_index('ix_service_payment_status')
        batch_op.drop_index('ix_service_payment_order')

    op.drop_table('service_payments')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segments_tenant_status')
        batch_op.drop_index(batch_op.f('ix_segments_tenant_id'))
        batch_op.drop_index('ix_segments_status')
        batch_op.drop_index(batch_op.f('ix_segments_id'))

    op.drop_table('segments')
    with op.batch_alter_table('route_stop_records', schema=None) as batch_op:
        batch_op.drop_index('ix_route_stop_route')

    op.drop_table('route_stop_records')
    with op.batch_alter_table('route_records', schema=None) as batch_op:
        batch_op.drop_index('ix_route_tenant')
        batch_op.drop_index('ix_route_status')
        batch_op.drop_index('ix_route_driver')

    op.drop_table('route_records')
    with op.batch_alter_table('receivables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receivables_tenant_id'))
        batch_op.drop_index('ix_receivables_status')
        batch_op.drop_index(batch_op.f('ix_receivables_order_codigo'))
        batch_op.drop_index('ix_receivables_order')
        batch_op.drop_index(batch_op.f('ix_receivables_id'))
        batch_op.drop_index('ix_receivables_due_date')
        batch_op.drop_index(batch_op.f('ix_receivables_customer_codigo'))
        batch_op.drop_index('ix_receivables_customer')

    op.drop_table('receivables')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_codigo'))

    op.drop_table('products')
    with op.batch_alter_table('pix_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_pix_config_tenant')

    op.drop_table('pix_configs')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_tenant_id'))
        batch_op.drop_index('ix_payments_status')
        batch_op.drop_index(batch_op.f('ix_payments_order_codigo'))
        batch_op.drop_index('ix_payments_order')
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index('ix_payments_created')

    op.drop_table('payments')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_method_tenant')

    op.drop_table('payment_methods')
    with op.batch_alter_table('outbox_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_tenant')
        batch_op.drop_index('ix_outbox_status')

    op.drop_table('outbox_entries')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_codigo'))
        batch_op.drop_index(batch_op.f('ix_orders_client_codigo'))

    op.drop_table('orders')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_codigo'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_product_codigo'))
        batch_op.drop_index(batch_op.f('ix_inventory_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_tenant')

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('financial_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_reference')
        batch_op.drop_index('ix_ledger_event_type')
        batch_op.drop_index('ix_ledger_created')
        batch_op.drop_index(batch_op.f('ix_financial_ledger_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_financial_ledger_id'))

    op.drop_table('financial_ledger')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_tenant_id'))
        batch_op.drop_index('ix_expenses_status')
        batch_op.drop_index(batch_op.f('ix_expenses_id'))
        batch_op.drop_index('ix_expenses_date')
        batch_op.drop_index('ix_expenses_category')

    op.drop_table('expenses')
    with op.batch_alter_table('driver_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_driver_session_tenant')
        batch_op.drop_index('ix_driver_session_driver')

    op.drop_table('driver_sessions')
    with op.batch_alter_table('driver_locations', schema=None) as batch_op:
        batch_op.drop_index('ix_driver_loc_tenant_driver')

    op.drop_table('driver_locations')
    with op.batch_alter_table('delivery_records', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_tenant_status')
        batch_op.drop_index('ix_delivery_tenant_driver')
        batch_op.drop_index(batch_op.f('ix_delivery_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_records_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_records_driver_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_records_delivery_id'))
        batch_op.drop_index('ix_delivery_order')

    op.drop_table('delivery_records')
    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_codigo'))

    op.drop_table('delivery_drivers')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_tipo')
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))
        batch_op.drop_index('ix_clients_telefone')
        batch_op.drop_index(batch_op.f('ix_clients_id'))
        batch_op.drop_index('ix_clients_email')
        batch_op.drop_index(batch_op.f('ix_clients_codigo'))
        batch_op.drop_index('ix_clients_ativo')

    op.drop_table('clients')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_cash_movements_type')
        batch_op.drop_index(batch_op.f('ix_cash_movements_tenant_id'))
        batch_op.drop_index('ix_cash_movements_reference')
        batch_op.drop_index(batch_op.f('ix_cash_movements_id'))
        batch_op.drop_index('ix_cash_movements_created')

    op.drop_table('cash_movements')
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_id'))

    op.drop_table('automation_rules')
    with op.batch_alter_table('automation_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_executions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_automation_executions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_automation_executions_id'))

    op.drop_table('automation_executions')
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_user_status')

    op.drop_table('auth_users')
    op.drop_table('auth_tenants')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_session_user')
        batch_op.drop_index('ix_auth_session_status')

    op.drop_table('auth_sessions')
    op.drop_table('auth_roles')
    with op.batch_alter_table('auth_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_membership_user')
        batch_op.drop_index('ix_auth_membership_tenant')

    op.drop_table('auth_memberships')
    with op.batch_alter_table('auth_audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_audit_timestamp')
        batch_op.drop_index('ix_auth_audit_tenant')
        batch_op.drop_index('ix_auth_audit_actor')

    op.drop_table('auth_audit_log')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_external_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_log_id'))

    op.drop_table('ai_audit_log')
    # ### end Alembic commands ###
